services:
  qdrant:
    image: qdrant/qdrant:v1.12.3
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./app/data/mysql/1-schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./app/data/mysql/2-data.sql:/docker-entrypoint-initdb.d/2-data.sql
    env_file:
      - .env

  backend:
    build: ./app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
      - mysql
      - redis
    env_file:
      - .env
      
  hash-passwords:
    build: ./app
    command: python scripts/hash_passwords.py
    depends_on:
      - mysql
    env_file:
      - .env
    volumes:
      - ./app:/app

  load-kb:
    build: ./app
    command: python scripts/load_kb_service.py
    depends_on:
      - mysql
      - qdrant
    env_file:
      - .env
    volumes:
      - ./app:/app

volumes:
  qdrant_data:
  mysql_data:
  redis_data:
